### ISSUE TITLE
Failed to set lockscreen

### ISSUE THREAD

**Issue by sofisofiloll** [Leapward-Koex/LockscreenGif#2]
I'm having a problem with setting the lockscreen. This is what the log on the txt. file says:
```
4:58 [INFO] App starting up. Running on Windows Microsoft Windows NT 10.0.19045.0
2024-11-05 11:16:33 [INFO] Trying to set lockscreen
2024-11-05 11:16:33 [INFO] User SID: S-1-5-21-1637566119-219826677-3030273235-1001. CurrentImage: C:\Users\sofia\OneDrive\Imágenes\windows-xp-loading-screen.gif
2024-11-05 11:16:33 [INFO] Calling default Windows API to set lockscreen image
2024-11-05 11:16:36 [INFO] Trying to take ownership of C:\ProgramData\Microsoft\Windows\SystemData\S-1-5-21-1637566119-219826677-3030273235-1001\ReadOnly
2024-11-05 11:16:54 [INFO] Checking permissions post ownership
2024-11-05 11:16:54 [INFO] LockScreen_A NT SERVICE\TrustedInstaller:(F)
2024-11-05 11:16:54 [INFO]              NT AUTHORITY\SYSTEM:(F)
2024-11-05 11:16:54 [INFO]              DESKTOP-J9567VI\sofia:(R)
2024-11-05 11:16:54 [INFO] 
2024-11-05 11:16:54 [INFO] LockScreen_O NT SERVICE\TrustedInstaller:(F)
2024-11-05 11:16:54 [INFO]              NT AUTHORITY\SYSTEM:(F)
2024-11-05 11:16:54 [INFO]              DESKTOP-J9567VI\sofia:(R)
2024-11-05 11:16:54 [INFO] 
2024-11-05 11:16:54 [INFO] LockScreen_W NT SERVICE\TrustedInstaller:(F)
2024-11-05 11:16:54 [INFO]              NT AUTHORITY\SYSTEM:(F)
2024-11-05 11:16:54 [INFO]              DESKTOP-J9567VI\sofia:(R)
2024-11-05 11:16:54 [INFO] 
2024-11-05 11:16:54 [INFO] LockScreen_A\LockScreen.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-05 11:16:54 [INFO]                             NT AUTHORITY\SYSTEM:(F)
2024-11-05 11:16:54 [INFO]                             DESKTOP-J9567VI\sofia:(R)
2024-11-05 11:16:54 [INFO] 
2024-11-05 11:16:54 [INFO] LockScreen_A\LockScreen___0108_0108.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-05 11:16:54 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-05 11:16:54 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-05 11:16:54 [INFO] 
2024-11-05 11:16:54 [INFO] LockScreen_A\LockScreen___0151_0151.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-05 11:16:54 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-05 11:16:54 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-05 11:16:54 [INFO] 
2024-11-05 11:16:54 [INFO] LockScreen_A\LockScreen___0194_0194.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-05 11:16:54 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-05 11:16:54 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-05 11:16:54 [INFO] 
2024-11-05 11:16:54 [INFO] LockScreen_O\LockScreen___1920_1080_notdimmed.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-05 11:16:54 [INFO]                                                   NT AUTHORITY\SYSTEM:(F)
2024-11-05 11:16:54 [INFO]                                                   DESKTOP-J9567VI\sofia:(R)
2024-11-05 11:16:54 [INFO] 
2024-11-05 11:16:54 [INFO] LockScreen_W\LockScreen___1920_1080_notdimmed.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-05 11:16:54 [INFO]                                                   NT AUTHORITY\SYSTEM:(F)
2024-11-05 11:16:54 [INFO]                                                   DESKTOP-J9567VI\sofia:(R)
2024-11-05 11:16:54 [INFO] 
2024-11-05 11:16:54 [INFO] Se procesaron correctamente 9 archivos; error al procesar 0 archivos
2024-11-05 11:16:54 [INFO] Trying to replace dimmed files with file extension spoofed GIF
2024-11-05 11:16:54 [INFO] Lockscreen images in paths C:\ProgramData\Microsoft\Windows\SystemData\S-1-5-21-1637566119-219826677-3030273235-1001\ReadOnly\LockScreen_A
2024-11-05 11:16:54 [INFO] Copying GIF to C:\ProgramData\Microsoft\Windows\SystemData\S-1-5-21-1637566119-219826677-3030273235-1001\ReadOnly\LockScreen_A\LockScreen___1920_1080_notdimmed.jpg
2024-11-05 11:16:55 [ERROR] Failed to set lockscreen
Exception: Attempted to perform an unauthorized operation.
StackTrace:    at LockscreenGif.Services.LockscreenService.<>c__DisplayClass12_0.<<CreateDimmedFiles>b__1>d.MoveNext() in D:\a\LockscreenGif\LockscreenGif\Services\LockscreenService.cs:line 120
--- End of stack trace from previous location ---
   at LockscreenGif.Services.LockscreenService.<CreateDimmedFiles>b__12_0(String folderPath) in D:\a\LockscreenGif\LockscreenGif\Services\LockscreenService.cs:line 122
   at LockscreenGif.Services.LockscreenService.CreateDimmedFiles(String lockscreenDirectory) in D:\a\LockscreenGif\LockscreenGif\Services\LockscreenService.cs:line 125
   at LockscreenGif.Services.LockscreenService.ApplyGifAsLockscreenAsync() in D:\a\LockscreenGif\LockscreenGif\Services\LockscreenService.cs:line 92

```
I can´t seem to find the path on the fourth [INFO] line. My PC is set in spanish and it´s windows 10, I also have my disk divided in 2. Could that be the problem?
Hope this is useful info <3

**Comment by Leapward-Koex** [comment]
Thanks for the report. I'm pretty sure I know the reason why this is happening.

Can you give this build a try and see if it works?
https://github.com/Leapward-Koex/LockscreenGif/releases/tag/1.2.2

**Comment by sofisofiloll** [comment]
I´m afraid not :( Here´s the txt:
```
024-11-07 09:42:45 [INFO] App starting up. Running on Windows Microsoft Windows NT 10.0.19045.0
2024-11-07 09:43:06 [INFO] Trying to set lockscreen
2024-11-07 09:43:06 [INFO] User SID: S-1-5-21-1637566119-219826677-3030273235-1001. CurrentImage: C:\Users\sofia\OneDrive\Imágenes\Windows_XP_Home_bootscreen.gif
2024-11-07 09:43:06 [INFO] Trying to take ownership of C:\ProgramData\Microsoft\Windows\SystemData\S-1-5-21-1637566119-219826677-3030273235-1001\ReadOnly
2024-11-07 09:43:06 [INFO] Checking permissions pre ownership
2024-11-07 09:43:06 [INFO] LockScreen_A NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:06 [INFO]              NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:06 [INFO]              DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:06 [INFO] 
2024-11-07 09:43:06 [INFO] LockScreen_B NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:06 [INFO]              NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:06 [INFO]              DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:06 [INFO] 
2024-11-07 09:43:06 [INFO] LockScreen_O NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:06 [INFO]              NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:06 [INFO]              DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:06 [INFO] 
2024-11-07 09:43:06 [INFO] LockScreen_W NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:06 [INFO]              NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:06 [INFO]              DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:06 [INFO] 
2024-11-07 09:43:06 [INFO] LockScreen_A\LockScreen.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:06 [INFO]                             NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:06 [INFO]                             DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:06 [INFO] 
2024-11-07 09:43:06 [INFO] LockScreen_A\LockScreen___0108_0108.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:06 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:06 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:06 [INFO] 
2024-11-07 09:43:07 [INFO] LockScreen_A\LockScreen___0151_0151.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:07 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:07 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:07 [INFO] 
2024-11-07 09:43:07 [INFO] LockScreen_A\LockScreen___0194_0194.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:07 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:07 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:07 [INFO] 
2024-11-07 09:43:07 [INFO] LockScreen_B\LockScreen.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:07 [INFO]                             NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:07 [INFO]                             DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:07 [INFO] 
2024-11-07 09:43:07 [INFO] LockScreen_B\LockScreen___0108_0108.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:07 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:07 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:07 [INFO] 
2024-11-07 09:43:07 [INFO] LockScreen_B\LockScreen___0151_0151.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:07 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:07 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:07 [INFO] 
2024-11-07 09:43:07 [INFO] LockScreen_B\LockScreen___0194_0194.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:07 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:07 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:07 [INFO] 
2024-11-07 09:43:07 [INFO] LockScreen_B\LockScreen___1920_1080_notdimmed.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:07 [INFO]                                                   NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:07 [INFO]                                                   DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:07 [INFO] 
2024-11-07 09:43:07 [INFO] LockScreen_O\LockScreen___1920_1080_notdimmed.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:07 [INFO]                                                   NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:07 [INFO]                                                   DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:07 [INFO] 
2024-11-07 09:43:07 [INFO] LockScreen_W\LockScreen___1920_1080_notdimmed.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:07 [INFO]                                                   NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:07 [INFO]                                                   DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:07 [INFO] 
2024-11-07 09:43:07 [INFO] Se procesaron correctamente 15 archivos; error al procesar 0 archivos
2024-11-07 09:43:25 [INFO] Checking permissions post ownership
2024-11-07 09:43:25 [INFO] LockScreen_A NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:25 [INFO]              NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:25 [INFO]              DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:25 [INFO] 
2024-11-07 09:43:25 [INFO] LockScreen_B NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:25 [INFO]              NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:25 [INFO]              DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:25 [INFO] 
2024-11-07 09:43:25 [INFO] LockScreen_O NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:25 [INFO]              NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:25 [INFO]              DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:25 [INFO] 
2024-11-07 09:43:25 [INFO] LockScreen_W NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:25 [INFO]              NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:25 [INFO]              DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:25 [INFO] 
2024-11-07 09:43:25 [INFO] LockScreen_A\LockScreen.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:25 [INFO]                             NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:25 [INFO]                             DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:25 [INFO] 
2024-11-07 09:43:25 [INFO] LockScreen_A\LockScreen___0108_0108.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:25 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:25 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:25 [INFO] 
2024-11-07 09:43:25 [INFO] LockScreen_A\LockScreen___0151_0151.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:25 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:25 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:25 [INFO] 
2024-11-07 09:43:25 [INFO] LockScreen_A\LockScreen___0194_0194.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:25 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:25 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:25 [INFO] 
2024-11-07 09:43:25 [INFO] LockScreen_B\LockScreen.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:25 [INFO]                             NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:25 [INFO]                             DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:25 [INFO] 
2024-11-07 09:43:25 [INFO] LockScreen_B\LockScreen___0108_0108.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:25 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:25 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:25 [INFO] 
2024-11-07 09:43:26 [INFO] LockScreen_B\LockScreen___0151_0151.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:26 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:26 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:26 [INFO] 
2024-11-07 09:43:26 [INFO] LockScreen_B\LockScreen___0194_0194.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:26 [INFO]                                         NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:26 [INFO]                                         DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:26 [INFO] 
2024-11-07 09:43:26 [INFO] LockScreen_B\LockScreen___1920_1080_notdimmed.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:26 [INFO]                                                   NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:26 [INFO]                                                   DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:26 [INFO] 
2024-11-07 09:43:26 [INFO] LockScreen_O\LockScreen___1920_1080_notdimmed.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:26 [INFO]                                                   NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:26 [INFO]                                                   DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:26 [INFO] 
2024-11-07 09:43:26 [INFO] LockScreen_W\LockScreen___1920_1080_notdimmed.jpg NT SERVICE\TrustedInstaller:(F)
2024-11-07 09:43:26 [INFO]                                                   NT AUTHORITY\SYSTEM:(F)
2024-11-07 09:43:26 [INFO]                                                   DESKTOP-J9567VI\sofia:(R)
2024-11-07 09:43:26 [INFO] 
2024-11-07 09:43:26 [INFO] Se procesaron correctamente 15 archivos; error al procesar 0 archivos
2024-11-07 09:43:26 [INFO] Trying to replace dimmed files with file extension spoofed GIF
2024-11-07 09:43:26 [INFO] Lockscreen images in paths C:\ProgramData\Microsoft\Windows\SystemData\S-1-5-21-1637566119-219826677-3030273235-1001\ReadOnly\LockScreen_A, C:\ProgramData\Microsoft\Windows\SystemData\S-1-5-21-1637566119-219826677-3030273235-1001\ReadOnly\LockScreen_B
2024-11-07 09:43:26 [INFO] Copying GIF to C:\ProgramData\Microsoft\Windows\SystemData\S-1-5-21-1637566119-219826677-3030273235-1001\ReadOnly\LockScreen_A\LockScreen___1920_1080_notdimmed.jpg
2024-11-07 09:43:26 [INFO] Copying GIF to C:\ProgramData\Microsoft\Windows\SystemData\S-1-5-21-1637566119-219826677-3030273235-1001\ReadOnly\LockScreen_B\LockScreen___1920_1080_notdimmed.jpg
2024-11-07 09:43:27 [ERROR] Failed to set lockscreen
Exception: Attempted to perform an unauthorized operation.
StackTrace:    at LockscreenGif.Services.LockscreenService.<>c__DisplayClass12_0.<<CreateDimmedFiles>b__1>d.MoveNext() in D:\a\LockscreenGif\LockscreenGif\LockScreenGif\Services\LockscreenService.cs:line 120
--- End of stack trace from previous location ---
   at LockscreenGif.Services.LockscreenService.<CreateDimmedFiles>b__12_0(String folderPath) in D:\a\LockscreenGif\LockscreenGif\LockScreenGif\Services\LockscreenService.cs:line 122
   at LockscreenGif.Services.LockscreenService.CreateDimmedFiles(String lockscreenDirectory) in D:\a\LockscreenGif\LockscreenGif\LockScreenGif\Services\LockscreenService.cs:line 125
   at LockscreenGif.Services.LockscreenService.ApplyGifAsLockscreenAsync() in D:\a\LockscreenGif\LockscreenGif\LockScreenGif\Services\LockscreenService.cs:line 92

```
Let me know if there´s any more info or data you need!

**Comment by Leapward-Koex** [comment]
Ok I've taken a different approach to trying to gain ownership of the required files, can you try this build and see if it works?
https://github.com/Leapward-Koex/LockscreenGif/releases/tag/1.2.3

**Comment by sofisofiloll** [comment]
It does! Thank you so much dude! Spanish windows ca be kinda weird I guess <3
